baseurl = "https://example.org/"
languageCode = "en-us"
title = "!CHAOS Control System"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Claudio Bisegni"
	description = "Control system based on Highly Abstracted and Open Structure."
	copyright = "Released under the EUPL license"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue-grey"
    	accent  = "teal"

  [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "digitalcraftsman"
	email   = "hello@email.com"


[[menu.main]]
	name   = "!CHAOS"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Documentation"
	url    = "documentation/"
	weight = 20

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 30


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
