image: baltig.infn.it:4567/bisegni/chaos-docker-compilation
cache:
  paths:
  - /builds/bisegni/chaosframework

build_framework:
  script:
    - echo $PWD
    - cmake -j  $(nproc) .
    - make  -j  $(nproc) ExperimentalStart
    - make  -j  $(nproc) ExperimentalConfigure
    - make  -j  $(nproc) ExperimentalBuild
    - make  -j  $(nproc) ExperimentalTest
  only:
    - development
