stages:
  - build
  - deploy
cache:
  key: $CI_BUILD_REF_NAME
  paths:
      - /builds/bisegni/chaosframework/config/CACHE
      - /builds/bisegni/chaosframework/external-*
      - /builds/bisegni/chaosframework/chaos-distrib-*

before_script:
  - export NOW=$(date +"%Y%m%d-%H%M%S")
  - export TAR_NAME_POSTFIX=$NOW
  - echo $CHAOS_DEPLOY_PRIVATE_KEY >> /builds/bisegni/chaosframework/deploy.key
  - chmod 600 /builds/bisegni/chaosframework/deploy.key

build_framework_x86_64:
  tag: docker shared
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
  script:
    - echo "Working directory:"$PWD
    - echo "Artifact name:"$TAR_NAME_POSTFIX
    - cmake .
    - make clean
    - make  -j 4
    - make install
    #- tar -zcf /builds/bisegni/chaosframework/chaos-distrib-x86_64-Linux_$TAR_NAME_POSTFIX.tgz /builds/bisegni/chaosframework/chaos-distrib-x86_64-Linux
    #- ls -la
    #- scp -v -i /builds/bisegni/chaosframework/deploy.key -o StrictHostKeyChecking=no /builds/bisegni/chaosframework/chaos-distrib-x86_64-Linux_$TAR_NAME_POSTFIX.tgz chaosweb@opensource.lnf.infn.it:/var/www/html/binary/chaos/
  only:
    - development
    - master

build_framework_arm:
  tag: docker shared
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
  script:
    - echo "Working directory:"$PWD
    - echo "Artifact name:"$TAR_NAME_POSTFIX
    - cmake -DCHAOS_TARGET=armhf
    - make clean
    - make  -j 4
    - make install
    #- tar -zcf /builds/bisegni/chaosframework/chaos-distrib-armhf_$TAR_NAME_POSTFIX.tgz /builds/bisegni/chaosframework/chaos-distrib-armhf
    #- ls -la
    #- scp -v -i /builds/bisegni/chaosframework/deploy.key -o StrictHostKeyChecking=no /builds/bisegni/chaosframework/chaos-distrib-x86_64-Linux_$TAR_NAME_POSTFIX.tgz chaosweb@opensource.lnf.infn.it:/var/www/html/binary/chaos/
  only:
    - development
    - master

deploy_framework_x86_64:
    stage: deploy
    image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
    script:
      - ls -la /builds/bisegni/chaosframework/chaos-distrib-x86_64-Linux/bin
      - ls -la /builds/bisegni/chaosframework/chaos-distrib-x86_64-Linux/lib
      - ls -la /builds/bisegni/chaosframework/chaos-distrib-x86_64-Linux/include
      - echo "scp /builds/bisegni/chaosframework/chaos-distrib-x86_64-Linux_$TAR_NAME_POSTFIX.tgz chaosweb@opensource.lnf.infn.it:/var/www/html/binary/chaos/"
    only:
      - development
      - master

deploy_framework_arm:
    stage: deploy
    image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
    script:
      - ls -la /builds/bisegni/chaosframework/chaos-distrib-armhf/bin
      - ls -la /builds/bisegni/chaosframework/chaos-distrib-armhf/lib
      - ls -la /builds/bisegni/chaosframework/chaos-distrib-armhf/include
      - echo "scp /builds/bisegni/chaosframework/chaos-distrib-armhf_$TAR_NAME_POSTFIX.tgz chaosweb@opensource.lnf.infn.it:/var/www/html/binary/chaos/"
    only:
      - development
      - master
