image: bisegni/chaos
cache:
  paths:
  - /builds/bisegni/chaosframework

build_framework:
  script:
    - echo $PWD
    - cmake .
    - make ExperimentalStart
    - make ExperimentalConfigure
    - make ExperimentalBuild
    - make ExperimentalTest
    - make ExperimentalSubmit
