stages:
  - build
  - deploy
cache:
  key: $CI_JOB_NAME/$CI_BUILD_REF_NAME
  paths:
      - /builds/chaos-lnf-control/chaosframework/config/CACHE
      - /builds/chaos-lnf-control/chaosframework/external-*
      - /builds/chaos-lnf-control/chaosframework/chaos-distrib-*

before_script:
  - export NOW=$(date +"%Y%m%d-%H%M%S")
  - export TAR_NAME_POSTFIX=$NOW
  - echo $CHAOS_DEPLOY_PRIVATE_KEY >> /builds/chaos-lnf-control/chaosframework/deploy.key
  - chmod 600 /builds/chaos-lnf-control/chaosframework/deploy.key

build_framework_x86_64:
  tags:
    - docker
    - shared
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
  script:
    - echo "Working directory:"$PWD
    - echo "Artifact name:"$TAR_NAME_POSTFIX
    - cmake .
    - make clean
    - make  -j 4
    - make install
  only:
    - development
    - master

build_framework_x86_64_c98:
  tags:
    - docker
    - shared
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
  script:
    - echo "Working directory:"$PWD
    - echo "Artifact name:"$TAR_NAME_POSTFIX
    - cmake -DCHAOS_ENABLE_C11=OFF .
    - make clean
    - make  -j 4
    - make install
  only:
    - development
    - master

build_framework_arm:
  tags:
    - docker
    - shared
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
  script:
    - echo "Working directory:"$PWD
    - echo "Artifact name:"$TAR_NAME_POSTFIX
    - cmake -DCHAOS_TARGET=armhf
    - make clean
    - make  -j 4
    - make install
  only:
    - development
    - master

exp_build_framework_x86_64:
  tags:
    - docker
    - shared
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
  script:
    - echo "Working directory:"$PWD
    - echo "Artifact name:"$TAR_NAME_POSTFIX
    - cmake .
    - make clean
    - make  -j 4
    - make install
  only:
    - schedules

exp_build_framework_x86_64_c98:
  tags:
    - docker
    - shared
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
  script:
    - echo "Working directory:"$PWD
    - echo "Artifact name:"$TAR_NAME_POSTFIX
    - cmake -DCHAOS_ENABLE_C11=OFF .
    - make clean
    - make  -j 4
    - make install
  only:
    - schedules

exp_build_framework_arm:
  tags:
    - docker
    - shared
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
  script:
    - echo "Working directory:"$PWD
    - echo "Artifact name:"$TAR_NAME_POSTFIX
    - cmake -DCHAOS_TARGET=armhf
    - make clean
    - make  -j 4
    - make install
  only:
    - schedules

exp_scan_coverity:
    tags:
      - docker
      - shared
    stage: build
    image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/coverity:latest
    script:
      - mkdir -p /tmp/cov-int
      - cmake .
      - make clean
      - /tmp/coverity/bin/cov-build --dir /tmp/cov-int make  -j 4
      - tar czvf /tmp/chaos.tgz /tmp/cov-int
      - curl --form token=i9B9MI9n53zWdx2iSS4Qvg --form email=bisegni@lnf.infn.it --form file=@/tmp/chaos.tgz --form version="1.0.0" --form description="Beta"  https://scan.coverity.com/builds?project=%21CHAOS+Control+System
    only:
      - web

    exp_scan_coverity:
        tags:
          - docker
          - shared
        stage: deploy
        image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/coverity:latest
        script:
          - mkdir -p /tmp/cov-int
          - cmake .
          - make clean
          - /tmp/coverity/bin/cov-build --dir /tmp/cov-int make  -j 4
          - tar czvf /tmp/chaos.tgz /tmp/cov-int
          - curl --form token=i9B9MI9n53zWdx2iSS4Qvg \
            --form email=bisegni@lnf.infn.it \
            --form file=/tmp/chaos.tgz \
            --form version="1.0.0" \
            --form description="Beta" \
            https://scan.coverity.com/builds?project=%21CHAOS+Control+System
        only:
          - web
#- tar -zcf /builds/chaos-lnf-control/chaosframework/chaos-distrib-armhf_$TAR_NAME_POSTFIX.tgz /builds/chaos-lnf-control/chaosframework/chaos-distrib-armhf
#- ls -la
#- scp -v -i /builds/chaos-lnf-control/chaosframework/deploy.key -o StrictHostKeyChecking=no /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux_$TAR_NAME_POSTFIX.tgz chaosweb@opensource.lnf.infn.it:/var/www/html/binary/chaos/

# deploy_framework_x86_64:
#     tags:
#       - docker
#       - shared
#     stage: deploy
#     image: baltig.infn.it:4567/chaos-lnf-control/chaos-docker-compilation:latest
#     script:
#       - ls -la /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux/bin
#       - ls -la /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux/lib
#       - ls -la /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux/include
#       - echo "scp /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux_$TAR_NAME_POSTFIX.tgz chaosweb@opensource.lnf.infn.it:/var/www/html/binary/chaos/"
#     only:
#       - development
#       - master
#
# deploy_framework_arm:
#     tags:
#       - docker
#       - shared
#     stage: deploy
#     image: baltig.infn.it:4567/chaos-lnf-control/chaos-docker-compilation:latest
#     script:
#       - ls -la /builds/chaos-lnf-control/chaosframework/chaos-distrib-armhf/bin
#       - ls -la /builds/chaos-lnf-control/chaosframework/chaos-distrib-armhf/lib
#       - ls -la /builds/chaos-lnf-control/chaosframework/chaos-distrib-armhf/include
#       - echo "scp /builds/chaos-lnf-control/chaosframework/chaos-distrib-armhf_$TAR_NAME_POSTFIX.tgz chaosweb@opensource.lnf.infn.it:/var/www/html/binary/chaos/"
#     only:
#       - development
#       - master
