stages:
  - build
  - test
  - quality
  - deploy
  - publish

before_script:
  - export NOW=$(date +"%Y%m%d-%H%M%S")
  - export TAR_NAME_POSTFIX=$NOW
  - export SYS=`uname -s`
  - export CHAOS_LIB_HASH=`git log -n 1 --pretty="%h"`

codequality:
  image: docker:stable
  stage: quality
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run --env SOURCE_CODE="$PWD" --volume "$PWD"/chaos:/code --volume /var/run/docker.sock:/var/run/docker.sock "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths: [codeclimate.json]

build_framework_x86_64:
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
  script:
    - tools/chaos_clean.sh
    - cmake -DCHAOS_ARCHITECTURE_TEST=ON -DCMAKE_BUILD_TYPE=PROFILE .
    - make clean
    - make  -j 4
    - make install
    - cd ccs
    - /Qt/5.9.3/gcc_64/bin/qmake
    - make -j 4
  cache:
    key: x86_64_$CI_BUILD_REF_NAME
    paths:
        - /builds/chaos-lnf-control/chaosframework/config/CACHE/
  artifacts:
    paths:
        - chaos
        - CHAOSFrameworkTests
        - 'chaos-distrib-x86_64-Linux'
    expire_in: 4 hour
  only:
    - experimental

build_framework_x86_64_test:
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: test
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
  script:
    - apt-get update
    - apt-get -y install lcov
    - export LD_LIBRARY_PATH=/builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux/lib
    - chaos-distrib-x86_64-Linux/bin/TestFramework
    - lcov -c -d chaos --output-file coverage.info
    - genhtml coverage.info --output-directory coverage_html
  artifacts:
    paths:
        - 'coverage_html'
    expire_in: 1 hour
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  only:
    - experimental

build_framework_centos7:
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/centos7:latest
  script:
    - tools/chaos_clean.sh
    - cmake -DCHAOS_ARCHITECTURE_TEST=ON .
    - make clean
    - make  -j 4
    - make install
    - cd ccs
    - /Qt/5.9.3/gcc_64/bin/qmake
    - make -j 4
    - mv /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-centos7
  cache:
    key: x86_64_centos7_$CI_BUILD_REF_NAME
    paths:
        - /builds/chaos-lnf-control/chaosframework/config/CACHE/
  artifacts:
    paths:
        - chaos
        - CHAOSFrameworkTests
        - 'chaos-distrib-x86_64-centos7'
    expire_in: 4 hour
  only:
    - experimental

execute_framework_centos7_test:
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: test
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/centos7:latest
  script:
    - export LD_LIBRARY_PATH=/builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-centos7/lib
    - chaos-distrib-x86_64-centos7/bin/TestFramework
  artifacts:
    paths:
        - 'chaos-distrib-x86_64-centos7'
    expire_in: 4 hour
  only:
    - experimental

execute_framework_centos7_deploy:
  tags:
    - lnf
  stage: deploy
  image: baltig.infn.it:4567/chaos-lnf-control/chaos_bundle_compilation:lite
  dependencies:
    - execute_framework_centos7_test
  script:
    - tar cfz chaos-distrib-x86_64-centos7_$TAR_NAME_POSTFIX.tar.gz chaos-distrib-x86_64-centos7
    - ls -la
    - scp chaos-distrib-x86_64-centos7_$TAR_NAME_POSTFIX.tar.gz chaosweb@opensource.lnf.infn.it:/var/www/html/binary/chaos/$CI_COMMIT_REF_NAME/x86_64/centos/7/chaos-distrib-x86_64-centos7_$TAR_NAME_POSTFIX.tar.gz
  only:
    - experimental

llvm_build_framework_x86_64:
  tags:
    - chaos
    - docker
    - linux
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/llvm_coverity_u1710
  script:
    - tools/chaos_clean.sh
    - cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCHAOS_ARCHITECTURE_TEST=ON .
    - make clean
    - make  -j 4
    - make install
    - mv /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux-llvm
  cache:
    key: llvm_x86_64_$CI_BUILD_REF_NAME
    paths:
        - /builds/chaos-lnf-control/chaosframework/config/CACHE/
  artifacts:
    paths:
        - chaos
        - CHAOSFrameworkTests
        - 'chaos-distrib-x86_64-Linux-llvm'
    expire_in: 4 hour
  only:
    - web

llvm_build_framework_x86_64_test:
  tags:
    - chaos
    - docker
    - linux
  stage: test
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/llvm_coverity_u1710
  dependencies:
    - llvm_build_framework_x86_64
  script:
    - export LD_LIBRARY_PATH=/builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux-llvm/lib
    - chaos-distrib-x86_64-Linux-llvm/bin/TestFramework
  only:
    - web

build_framework_x86_64_c98:
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
  script:
    - tools/chaos_clean.sh
    - cmake -DCHAOS_ENABLE_C11=OFF -DCHAOS_ARCHITECTURE_TEST=ON -DCMAKE_BUILD_TYPE=PROFILE .
    - make clean
    - make  -j 4
    - make install
    - mv /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux-c98
  cache:
    key: x86_64_c98_$CI_BUILD_REF_NAME
    paths:
        - /builds/chaos-lnf-control/chaosframework/config/CACHE/
  artifacts:
    paths:
        - 'chaos-distrib-x86_64-Linux-c98'
    expire_in: 4 hour
  only:
    - experimental

build_framework_x86_64_c98_test:
  tags:
    - chaos
    - docker
    - linux
  stage: test
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
  script:
    - export LD_LIBRARY_PATH=/builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux-c98/lib
    - chaos-distrib-x86_64-Linux-c98/bin/TestFramework
  only:
    - experimental

build_framework_arm:
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
  script:
    - tools/chaos_clean.sh
    - cmake -DCHAOS_TARGET=armhf .
    - make clean
    - make  -j 4
    - make install
  cache:
    key: arm-compilation_$CI_BUILD_REF_NAME
    paths:
        - /builds/chaos-lnf-control/chaosframework/config/CACHE/
  artifacts:
    paths:
        - 'chaos-distrib-armhf'
    expire_in: 4 hour
  only:
    - experimental

# build_framework_arm_test:
#   tags:
#     - chaos
#     - docker
#     - linux
#   stage: test
#   image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
#   script:
#     - export LD_LIBRARY_PATH=/builds/chaos-lnf-control/chaosframework/chaos-distrib-armhf
#     - chaos-distrib-armhf/bin/FrameworkTest
#   only:
#     - development
#     - master
#     - schedules
#     - web

# exp_llvm_scan_coverity:
#     tags:
#       - chaos
#       - docker
#       - linux
#     stage: build
#     image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/llvm_coverity_u1710
#     script:
#       - mkdir -p /tmp/cov-int
#       - cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCHAOS_ARCHITECTURE_TEST=ON .
#       - make clean
#       - /tmp/coverity/bin/cov-build --dir /tmp/cov-int make -j 4
#       - cd /tmp
#       - tar czvf chaos.tgz cov-int
#       - curl --form token=i9B9MI9n53zWdx2iSS4Qvg --form email=bisegni@lnf.infn.it --form file=@/tmp/chaos.tgz --form version="1.0.0" --form description="Beta"  https://scan.coverity.com/builds?project=%21CHAOS+Control+System
#     cache:
#       key: scan_coverity_$CI_BUILD_REF_NAME
#       paths:
#           - /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux/
#           - /builds/chaos-lnf-control/chaosframework/config/CACHE/
#     only:
#       - web

pages:
  stage: publish
  dependencies:
    - build_framework_x86_64_test
  script:
    - mv coverage_html public
    - ls -la
  artifacts:
    paths:
      - public
    expire_in: 7 days
  only:
    - experimental
