cache:
  paths:
  - /builds/bisegni/chaosframework

stages:
  - build
  - deploy

before_script:
  - export NOW=$(date +"%Y%m%d-%H%M%S")
  - export TAR_NAME_POSTFIX=$NOW

build_framework_x86_64:
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
  script:
    - echo "Working directory:"$PWD
    - echo "Artifact name:"$TAR_NAME_POSTFIX
    - cmake -DCHAOS_ARCHITECTURE_TEST=ON .
    - make  -j  $(nproc) ExperimentalStart
    - make  -j  $(nproc) ExperimentalConfigure
    - make  -j  $(nproc) ExperimentalBuild
    - tar -zcf /builds/bisegni/chaosframework/chaos-distrib-x86_64-Linux_$TAR_NAME_POSTFIX.tgz /builds/bisegni/chaosframework/chaos-distrib-x86_64-Linux
  artifacts:
    name: "chaos-distrib-x86_64-Linux_$(TAR_NAME_POSTFIX)"
    paths:
      - /builds/bisegni/chaosframework/chaos-distrib-x86_64-Linux_$TAR_NAME_POSTFIX.tgz

  only:
    - development
    - master

build_framework_arm:
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
  script:
    - echo "Working directory:"$PWD
    - echo "Artifact name:"$TAR_NAME_POSTFIX
    - cmake -DCHAOS_TARGET=armhf
    - make  -j  $(nproc) ExperimentalStart
    - make  -j  $(nproc) ExperimentalConfigure
    - make  -j  $(nproc) ExperimentalBuild
    - tar -zcf /builds/bisegni/chaosframework/chaos-distrib-armhf_$TAR_NAME_POSTFIX.tgz /builds/bisegni/chaosframework/chaos-distrib-armhf
  artifacts:
    name: "chaos-distrib-x86_64-Linux_$(TAR_NAME_POSTFIX)"
    paths:
      - /builds/bisegni/chaosframework/chaos-distrib-armhf_$TAR_NAME_POSTFIX.tgz
  only:
    - development
    - master

deploy_framework_x86_64:
    stage: deploy
    image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
    script:
      - echo "scp /builds/bisegni/chaosframework/chaos-distrib-x86_64-Linux_$TAR_NAME_POSTFIX.tgz chaosweb@opensource.lnf.infn.it:/var/www/html/binary/chaos/"

deploy_framework_arm:
    stage: deploy
    image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
    script:
      - echo "scp /builds/bisegni/chaosframework/chaos-distrib-armhf_$TAR_NAME_POSTFIX.tgz chaosweb@opensource.lnf.infn.it:/var/www/html/binary/chaos/"
