stages:
- name: build
  steps:
  - runScriptConfig:
      image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/centos7:devtools7
      shellScript: |-
        export NPROC=$(nproc --ignore 1)
        cmake -DCHAOS_AGENT=OFF -DCHAOSHITECTURE_TEST=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo .
        make clean
        make  -j $NPROC
        make install
    envFrom:
    - sourceName: s3access
      sourceKey: AccessKey
timeout: 60
notification:
  recipients:
  - recipient: '#chaosframework'
    notifier: c-8rpc8:n-l9l78
  condition:
  - Success
  - Failed
