stages:
- name: build
  steps:
  - runScriptConfig:
      image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/centos7:devtools7
      shellScript: |-
        export NPROC=$(nproc --ignore 1)
        cmake -DCHAOS_AGENT=OFF -DCHAOS_VERSION_MAJOR="${CICD_GIT_BRANCH}" -DCHAOS_VERSION_MINOR="${CICD_GIT_COMMIT}" -DCHAOS_BUILD_ID="${CICD_PIPELINE_ID}"-DCHAOS_ARCHITECTURE_TEST=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo .
        make clean
        make  -j $NPROC
        make install
timeout: 60
notification:
  recipients:
  - recipient: '#chaosframework'
    notifier: c-8rpc8:n-l9l78
  condition:
  - Success
  - Failed
