stages:
- name: build
  steps:
  - runScriptConfig:
      image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/centos7:devtools7
      shellScript: |-
        export NPROC=$(nproc --ignore 1)
        cmake -DCHAOS_AGENT=OFF -DCHAOS_VERSION_MAJOR="$CI_COMMIT_REF_NAME.$CHAOS_LIB_HASH" -DCHAOS_VERSION_MINOR="$CI_JOB_STAGE.$CI_COMMIT_SHA" -DCHAOS_BUILD_ID=${CI_PIPELINE_ID} -DCHAOS_ARCHITECTURE_TEST=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo .
        make clean
        make  -j $NPROC
        make install
timeout: 60
notification:
  recipients:
  - recipient: '#chaosframework'
    notifier: c-8rpc8:n-l9l78
  condition:
  - Success
  - Failed
